
using Exceptions.Exceptions;
using System.Net.Http.Headers;






int x = 3;
int y = 0;


try
{
    Console.WriteLine(x/y);

}
catch(c ex)
{
    
}
finally
{

}
class c:Exception
{

}
//Console.WriteLine("Before test method");
//test();
//Console.WriteLine("After test method");

//void test()
//{
//    try
//    {
//        Login(null, "123");
//    }
//    catch (LoginException l) when (x > 0)
//    {
//        Console.WriteLine(l.Message);
//        Console.WriteLine(l.Date);
//        Console.WriteLine(l.User);
//    }
//    finally
//    {

//    }
//}
//void Login(string username, string password)
//{
//    if (username == null || password == null)
//    {
//        throw new LoginException(username);
//    }
//}


